---
title: "CodeBookForRunAnalysis"
author: "DS"
date: "August 23, 2015"
output: html_document
---

# Getting and Cleaning Data course assignment
See the README file for an overview of the assignment.

Unless otherwise noted, information about the data is from UCI Machine Learning Repository. Endnotes are provided to identify specific pages.

## Original data
"The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

"The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain." [2]

###Data and units overview

 - "Features are normalized and bounded within [-1,1].
 - "Each feature vector is a row on the text file." [2]
 - "the accelerations (total and body) are 'g's (gravity of earth -> 9.80665 m/seg2).
 - "The gyroscope units are rad/seg." [2]

###Data details
"The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

"Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

"Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

"These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

 - "tBodyAcc-XYZ
- "tGravityAcc-XYZ
- "tBodyAccJerk-XYZ
- "tBodyGyro-XYZ
- "tBodyGyroJerk-XYZ
- "tBodyAccMag
- "tGravityAccMag
- "tBodyAccJerkMag
- "tBodyGyroMag
- "tBodyGyroJerkMag
- "fBodyAcc-XYZ
- "fBodyAccJerk-XYZ
- "fBodyGyro-XYZ
- "fBodyAccMag
- "fBodyAccJerkMag
- "fBodyGyroMag
- "fBodyGyroJerkMag" [3]

The data included mean, standard deviation, median absolute deviation, maximum value, minimum value, signal magnitude area, energy measure, interquartile range, signal entropy, autoregression coefficients, correlation coefficient, index of the frequency component with largest magnitude, Weighted average of the frequency components to obtain a mean frequency, skewness of the frequency domain signal, kurtosis of the frequency domain signal, energy of a frequency interval within the 64 bins of the FFT of each window, angle between to vectors [3].Per assigment instructions, only mean and standard deviation were used in this work.



###Files used

 - features.txt: Provided the variable names for the x_test and x_train data
 - activity_labels.txt: used to translate the activity codes to names (WALKING,            WALKING_UPSTAIRS, WALKING_DOWNSTAIRS,SITTING, STANDING, LAYING)
 - x_test.txt and X_train.txt: core data
 - y_test.txt and y_train.txt: provided the activity codes
 - subject_test and subject_train: provided the subject identification codes


##Transformations
Per the assignment instructions, the mean and standard deviation (std) were used, and the average (mean) was taken for all of this data.

##Resources
[1] UCI Machine Learning Repository main page http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

[2] Human Activity Recognition Using Smartphones Dataset http://archive.ics.uci.edu/ml/machine-learning-databases/00240/UCI%20HAR%20Dataset.names

[3] features.txt file from the dataset https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip 

##Main source citation
Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. A Public Domain Dataset for Human Activity Recognition Using Smartphones. 21th European Symposium on Artificial Neural Networks, Computational Intelligence and Machine Learning, ESANN 2013. Bruges, Belgium 24-26 April 2013.

